plugins {
    id 'java'
    id "io.freefair.lombok" version "8.13"
}

group 'run.halo.gallery'
version project.findProperty('version') ?: '1.0.0-SNAPSHOT'

repositories {
    mavenCentral()
    mavenLocal()
    maven { url 'https://s01.oss.sonatype.org/content/repositories/snapshots/' }
}

def haloVersion = '2.24.0'
def springBootVersion = '3.4.5'

dependencies {
    compileOnly "run.halo.app:api:${haloVersion}"
    compileOnly "org.springframework.boot:spring-boot-starter-webflux:${springBootVersion}"
    compileOnly "org.springframework.data:spring-data-commons:${springBootVersion}"
    compileOnly "org.springdoc:springdoc-openapi-starter-webflux-ui:2.8.6"
    compileOnly "org.pf4j:pf4j:3.12.0"
    compileOnly "io.swagger.core.v3:swagger-annotations:2.2.28"
    compileOnly "io.swagger.core.v3:swagger-models:2.2.28"
    compileOnly "io.swagger.parser.v3:swagger-parser:2.1.24"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release = 21
}

jar {
    enabled = true
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from('src/main/resources') {
        include '**/*'
    }
}
